services:
  - type: web
    name: jarvis-pinnacle-terminal
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT --workers 2 --threads 4 wsgi_application:application"
    plan: free
    autoDeploy: true
